

```{r}
rm(list=ls())
```


```{r}
EEG.results.ordered = read.csv("~/Desktop/Final Mouse Data Application/EEG.results.ordered.csv")
subject.IDs = EEG.results.ordered$subject.ID
subject.IDs

color.labels = c(rep("red", 25), rep("blue", 18))
color.labels
```


```{r}
hsp = readRDS(file = "/Users/ziyisong/Desktop/HSP.MAD.NP/43.subjects/23.5.20.03300015.20000.RDS")

library(mcclust)
library("mcclust.ext")
source("/Users/ziyisong/Desktop/Project_HSP/F1Measure.R")
source("~/Desktop/Project_HSP/relabel.R")

R = 20000

seq_thin = seq(R*0.3, R, by=1)

results = hsp
MCMClabels = results$partition_c_iterations[seq_thin, ]
psm = comp.psm(MCMClabels)
avg = minVI(psm, MCMClabels, method=("all"), include.greedy=TRUE)
c.AUC.vi = relabel( avg$cl[1,] )
c.AUC.vi

table(c.AUC.vi)

pi.matrix.AUC.original = matrix(NA, ncol=43, nrow=6)
for (j in 1:43){
  MCMClabels_pi = results$pi_partitions_iterations[[j]][seq_thin, ]
  psm = comp.psm(MCMClabels_pi)
  avg = minVI(psm, MCMClabels_pi, method=("all"), include.greedy=TRUE)
  pi.matrix.AUC.original[ ,j] = avg$cl[1,]
}

subject.id.AUC.original = seq(1,43)
subject.id.AUC.rearrange = c()

cardinality.c = max(c.AUC.vi)
pi.matrix.AUC.rearrange = cbind()
for (i in 1:cardinality.c){
  index = which(c.AUC.vi == i)
  pi.matrix.AUC.rearrange = cbind(pi.matrix.AUC.rearrange, pi.matrix.AUC.original[,index])
  subject.id.AUC.rearrange = c(subject.id.AUC.rearrange, index)
}

for (j in 1:43){
  pi.matrix.AUC.rearrange[,j] = relabel(pi.matrix.AUC.rearrange[,j])
}


MCMClabels = results$partition_c_iterations[seq_thin, ]
psm = comp.psm(MCMClabels)
pp.subs.23.5.20=Heatmap(
        psm[subject.id.AUC.rearrange, subject.id.AUC.rearrange],
        # col = viridis::viridis(100),
        col = brewer.pal(n=4, name="Blues"),
        cluster_rows = F,cluster_columns = F,
        name = "Posterior\nCoclustering\nProbability",
        row_labels=subject.IDs[subject.id.AUC.rearrange],
        row_title = "subjects",
        row_names_side = "left",
        column_labels=subject.IDs[subject.id.AUC.rearrange],
        #column_title = "subjects", 
        show_heatmap_legend = T,
        column_split = paste0("Set \n",as.character(sort(c.AUC.vi))),
        column_title_side = "top",
        #column_split = as.character(sort(c.AUC.vi)),
        row_split = as.character(sort(c.AUC.vi)),
        row_names_gp = gpar(col = color.labels[subject.id.AUC.rearrange]),
        column_names_gp = gpar(col = color.labels[subject.id.AUC.rearrange])
          )
pp.subs.23.5.20


library(corrplot)

for ( i in 1:max(sort(c.AUC.vi)) ){
  subjects = subject.id.AUC.rearrange[sort(c.AUC.vi) == i]
  psm = matrix(0, nrow=6, ncol=6)
  for (s in subjects){
    psm = psm + comp.psm(results$pi_partitions_iterations[[s]][seq_thin, ])
  }
  psm = psm / length(subjects)
  
  colnames(psm) = c("CP-NP", "PH-NP", "UH-NP", "NP-CP", "NP-PH", "NP-UH")
  rownames(psm) = c("CP-NP", "PH-NP", "UH-NP", "NP-CP", "NP-PH", "NP-UH")
  
  right.order = c("NP-PH", "NP-UH", "NP-CP", "PH-NP", "UH-NP", "CP-NP")
  
  pdf(
    paste0("/Users/ziyisong/Desktop/HSP.MAD.NP/43.subjects/23.5.20.set",i,".pdf"),
    width=8, height=8)
  p = corrplot(psm[right.order, right.order], method="color", type="lower", diag=FALSE,
         addCoef.col = 'red', col.lim=c(0,1), tl.col="black", tl.srt=20,
         title=paste0("Set ", i), mar=c(0,0,1,0) )
  p
  dev.off()
}
```



```{r}
hsp = readRDS(file = "/Users/ziyisong/Desktop/HSP.MAD.NP/43.subjects/20.5.20.03300041.20000.RDS")

library(mcclust)
library("mcclust.ext")
source("/Users/ziyisong/Desktop/Project_HSP/F1Measure.R")
source("~/Desktop/Project_HSP/relabel.R")

R = 20000

seq_thin = seq(R*0.3, R, by=1)

results = hsp
MCMClabels = results$partition_c_iterations[seq_thin, ]
psm = comp.psm(MCMClabels)
avg = minVI(psm, MCMClabels, method=("all"), include.greedy=TRUE)
c.AUC.vi = relabel( avg$cl[1,] )
c.AUC.vi

table(c.AUC.vi)

pi.matrix.AUC.original = matrix(NA, ncol=43, nrow=6)
for (j in 1:43){
  MCMClabels_pi = results$pi_partitions_iterations[[j]][seq_thin, ]
  psm = comp.psm(MCMClabels_pi)
  avg = minVI(psm, MCMClabels_pi, method=("all"), include.greedy=TRUE)
  pi.matrix.AUC.original[ ,j] = avg$cl[1,]
}

subject.id.AUC.original = seq(1,43)
subject.id.AUC.rearrange = c()

cardinality.c = max(c.AUC.vi)
pi.matrix.AUC.rearrange = cbind()
for (i in 1:cardinality.c){
  index = which(c.AUC.vi == i)
  pi.matrix.AUC.rearrange = cbind(pi.matrix.AUC.rearrange, pi.matrix.AUC.original[,index])
  subject.id.AUC.rearrange = c(subject.id.AUC.rearrange, index)
}

for (j in 1:43){
  pi.matrix.AUC.rearrange[,j] = relabel(pi.matrix.AUC.rearrange[,j])
}


MCMClabels = results$partition_c_iterations[seq_thin, ]
psm = comp.psm(MCMClabels)
pp.subs.20.5.20=Heatmap(
        psm[subject.id.AUC.rearrange, subject.id.AUC.rearrange],
        # col = viridis::viridis(100),
        col = brewer.pal(n=4, name="Blues"),
        cluster_rows = F,cluster_columns = F,
        name = "Posterior\nCoclustering\nProbability",
        row_labels=subject.IDs[subject.id.AUC.rearrange],
        row_title = "subjects",
        row_names_side = "left",
        column_labels=subject.IDs[subject.id.AUC.rearrange],
        #column_title = "subjects", 
        show_heatmap_legend = T,
        column_split = paste0("Set \n",as.character(sort(c.AUC.vi))),
        column_title_side = "top",
        #column_split = as.character(sort(c.AUC.vi)),
        row_split = as.character(sort(c.AUC.vi)),
        row_names_gp = gpar(col = color.labels[subject.id.AUC.rearrange]),
        column_names_gp = gpar(col = color.labels[subject.id.AUC.rearrange])
          )
pp.subs.20.5.20


library(corrplot)

for ( i in 1:max(sort(c.AUC.vi)) ){
  subjects = subject.id.AUC.rearrange[sort(c.AUC.vi) == i]
  psm = matrix(0, nrow=6, ncol=6)
  for (s in subjects){
    psm = psm + comp.psm(results$pi_partitions_iterations[[s]][seq_thin, ])
  }
  psm = psm / length(subjects)
  
  colnames(psm) = c("CP-NP", "PH-NP", "UH-NP", "NP-CP", "NP-PH", "NP-UH")
  rownames(psm) = c("CP-NP", "PH-NP", "UH-NP", "NP-CP", "NP-PH", "NP-UH")
  
  right.order = c("NP-PH", "NP-UH", "NP-CP", "PH-NP", "UH-NP", "CP-NP")
  
  pdf(
    paste0("/Users/ziyisong/Desktop/HSP.MAD.NP/43.subjects/20.5.20.set",i,".pdf"),
    width=8, height=8)
  p = corrplot(psm[right.order, right.order], method="color", type="lower", diag=FALSE,
         addCoef.col = 'red', col.lim=c(0,1), tl.col="black", tl.srt=20,
         title=paste0("Set ", i), mar=c(0,0,1,0) )
  p
  dev.off()
}
```






```{r}
hsp = readRDS(file = "/Users/ziyisong/Desktop/HSP.MAD.NP/43.subjects/0.5.20.03300022.20000.RDS")

library(mcclust)
library("mcclust.ext")
source("/Users/ziyisong/Desktop/Project_HSP/F1Measure.R")
source("~/Desktop/Project_HSP/relabel.R")

R = 20000

seq_thin = seq(R*0.3, R, by=1)

results = hsp
MCMClabels = results$partition_c_iterations[seq_thin, ]
psm = comp.psm(MCMClabels)
avg = minVI(psm, MCMClabels, method=("all"), include.greedy=TRUE)
c.AUC.vi = relabel( avg$cl[1,] )
c.AUC.vi

table(c.AUC.vi)

pi.matrix.AUC.original = matrix(NA, ncol=43, nrow=6)
for (j in 1:43){
  MCMClabels_pi = results$pi_partitions_iterations[[j]][seq_thin, ]
  psm = comp.psm(MCMClabels_pi)
  avg = minVI(psm, MCMClabels_pi, method=("all"), include.greedy=TRUE)
  pi.matrix.AUC.original[ ,j] = avg$cl[1,]
}

subject.id.AUC.original = seq(1,43)
subject.id.AUC.rearrange = c()

cardinality.c = max(c.AUC.vi)
pi.matrix.AUC.rearrange = cbind()
for (i in 1:cardinality.c){
  index = which(c.AUC.vi == i)
  pi.matrix.AUC.rearrange = cbind(pi.matrix.AUC.rearrange, pi.matrix.AUC.original[,index])
  subject.id.AUC.rearrange = c(subject.id.AUC.rearrange, index)
}

for (j in 1:43){
  pi.matrix.AUC.rearrange[,j] = relabel(pi.matrix.AUC.rearrange[,j])
}


MCMClabels = results$partition_c_iterations[seq_thin, ]
psm = comp.psm(MCMClabels)
pp.subs.0.5.20=Heatmap(
        psm[subject.id.AUC.rearrange, subject.id.AUC.rearrange],
        # col = viridis::viridis(100),
        col = brewer.pal(n=4, name="Blues"),
        cluster_rows = F,cluster_columns = F,
        name = "Posterior\nCoclustering\nProbability",
        row_labels=subject.IDs[subject.id.AUC.rearrange],
        row_title = "subjects",
        row_names_side = "left",
        column_labels=subject.IDs[subject.id.AUC.rearrange],
        #column_title = "subjects", 
        show_heatmap_legend = T,
        column_split = paste0("Set \n",as.character(sort(c.AUC.vi))),
        column_title_side = "top",
        #column_split = as.character(sort(c.AUC.vi)),
        row_split = as.character(sort(c.AUC.vi)),
        row_names_gp = gpar(col = color.labels[subject.id.AUC.rearrange]),
        column_names_gp = gpar(col = color.labels[subject.id.AUC.rearrange])
          )
pp.subs.0.5.20


library(corrplot)

for ( i in 1:max(sort(c.AUC.vi)) ){
  subjects = subject.id.AUC.rearrange[sort(c.AUC.vi) == i]
  psm = matrix(0, nrow=6, ncol=6)
  for (s in subjects){
    psm = psm + comp.psm(results$pi_partitions_iterations[[s]][seq_thin, ])
  }
  psm = psm / length(subjects)
  
  colnames(psm) = c("CP-NP", "PH-NP", "UH-NP", "NP-CP", "NP-PH", "NP-UH")
  rownames(psm) = c("CP-NP", "PH-NP", "UH-NP", "NP-CP", "NP-PH", "NP-UH")
  
  right.order = c("NP-PH", "NP-UH", "NP-CP", "PH-NP", "UH-NP", "CP-NP")
  
  pdf(
    paste0("/Users/ziyisong/Desktop/HSP.MAD.NP/43.subjects/0.5.20.set",i,".pdf"),
    width=8, height=8)
  p = corrplot(psm[right.order, right.order], method="color", type="lower", diag=FALSE,
         addCoef.col = 'red', col.lim=c(0,1), tl.col="black", tl.srt=20,
         title=paste0("Set ", i), mar=c(0,0,1,0) )
  p
  dev.off()
}
```



```{r}
pdf("/Users/ziyisong/Desktop/HSP.MAD.NP/43.subjects/subjects.coclust.23.5.20.pdf",
    width=8, height=8)
pp.subs.23.5.20
dev.off()

pdf("/Users/ziyisong/Desktop/HSP.MAD.NP/43.subjects/subjects.coclust.20.5.20.pdf",
    width=8, height=8)
pp.subs.20.5.20
dev.off()

pdf("/Users/ziyisong/Desktop/HSP.MAD.NP/43.subjects/subjects.coclust.0.5.20.pdf",
    width=8, height=8)
pp.subs.0.5.20
dev.off()
```





