#!/bin/bash

#SBATCH --job-name=BCPlaidSimulationsTF    ## Name of the job.
#SBATCH -A vberroca_yoyo    ## account to charge 
#SBATCH -p standard          ## partition/queue name
#SBATCH --nodes=1            ## (-N) number of nodes to use
#SBATCH --ntasks=1          ## (-n) number of tasks to launch
#SBATCH --cpus-per-task=1    ## number of cores the job needs
#SBATCH -o BCPlaidSimulationsout.out

module load R/4.1.2
module load gcc/8.4.0
Rscript BCPlaidSimulations.R $1 




