

```{r}
rm(list=ls())
```



```{r}
ari_HSP.subjects.avg0.1 = readRDS("/Users/ziyisong/Desktop/Project_HSP/new.simulations/compare.HSP.NoBLoC/Contamination0.1/contamination0.1.ari_HSP.subjects.avg.RDS")
f1measure_HSP.subjects.avg0.1 = readRDS("/Users/ziyisong/Desktop/Project_HSP/new.simulations/compare.HSP.NoBLoC/Contamination0.1/contamination0.1.f1measure_HSP.subjects.avg.RDS")
ari_NoBLoC.subjects.avg0.1 = readRDS("/Users/ziyisong/Desktop/Project_HSP/new.simulations/compare.HSP.NoBLoC/Contamination0.1/contamination0.1.ari_NoBLoC.subjects.avg.RDS")
f1measure_NoBLoC.subjects.avg0.1 = readRDS("/Users/ziyisong/Desktop/Project_HSP/new.simulations/compare.HSP.NoBLoC/Contamination0.1/contamination0.1.f1measure_NoBLoC.subjects.avg.RDS")


ari_HSP.subjects.avg0.2 = readRDS("/Users/ziyisong/Desktop/Project_HSP/new.simulations/compare.HSP.NoBLoC/Contamination0.2/contamination0.2.ari_HSP.subjects.avg.RDS")
f1measure_HSP.subjects.avg0.2 = readRDS("/Users/ziyisong/Desktop/Project_HSP/new.simulations/compare.HSP.NoBLoC/Contamination0.2/contamination0.2.f1measure_HSP.subjects.avg.RDS")
ari_NoBLoC.subjects.avg0.2 = readRDS("/Users/ziyisong/Desktop/Project_HSP/new.simulations/compare.HSP.NoBLoC/Contamination0.2/contamination0.2.ari_NoBLoC.subjects.avg.RDS")
f1measure_NoBLoC.subjects.avg0.2 = readRDS("/Users/ziyisong/Desktop/Project_HSP/new.simulations/compare.HSP.NoBLoC/Contamination0.2/contamination0.2.f1measure_NoBLoC.subjects.avg.RDS")


ari_HSP.subjects.avg0.3 = readRDS("/Users/ziyisong/Desktop/Project_HSP/new.simulations/compare.HSP.NoBLoC/Contamination0.3/contamination0.3.ari_HSP.subjects.avg.RDS")
f1measure_HSP.subjects.avg0.3 = readRDS("/Users/ziyisong/Desktop/Project_HSP/new.simulations/compare.HSP.NoBLoC/Contamination0.3/contamination0.3.f1measure_HSP.subjects.avg.RDS")
ari_NoBLoC.subjects.avg0.3 = readRDS("/Users/ziyisong/Desktop/Project_HSP/new.simulations/compare.HSP.NoBLoC/Contamination0.3/contamination0.3.ari_NoBLoC.subjects.avg.RDS")
f1measure_NoBLoC.subjects.avg0.3 = readRDS("/Users/ziyisong/Desktop/Project_HSP/new.simulations/compare.HSP.NoBLoC/Contamination0.3/contamination0.3.f1measure_NoBLoC.subjects.avg.RDS")
```



```{r}
library("reshape2")
library("ggplot2")
dat = data.frame("10 %" = c(ari_HSP.subjects.avg0.1, ari_NoBLoC.subjects.avg0.1),
           "20 %" = c(ari_HSP.subjects.avg0.2, ari_NoBLoC.subjects.avg0.2),
           "30 %" = c(ari_HSP.subjects.avg0.3, ari_NoBLoC.subjects.avg0.3),
           Model = c(rep("HSP",50), rep("NoB-LoC",50)),
           check.names = FALSE
           )

dat_long = melt(dat, id="Model")

ggplot(dat_long, aes(x=variable, y=value, color=Model)) +
  geom_boxplot(notch=FALSE) +
  labs(title="(averaged across subjects) ARI: \n clustering conditions", 
       x="Contamination Level", y="Adjusted Rand Index") +
  #ylim(0,1) +
  theme_classic()
ggsave("HSP.NoBLoC.contamination.conditions.ari.pdf", 
       width=5, height=3.5)
```



```{r}
dat = data.frame("10 %" = c(f1measure_HSP.subjects.avg0.1, f1measure_NoBLoC.subjects.avg0.1),
           "20 %" = c(f1measure_HSP.subjects.avg0.2, f1measure_NoBLoC.subjects.avg0.2),
           "30 %" = c(f1measure_HSP.subjects.avg0.3, f1measure_NoBLoC.subjects.avg0.3),
           Model = c(rep("HSP",50), rep("NoB-LoC",50)),
           check.names = FALSE
           )

dat_long = melt(dat, id="Model")

ggplot(dat_long, aes(x=variable, y=value, color=Model)) +
  geom_boxplot(notch=FALSE) +
  labs(title="(averaged across subjects) F1-Measure:\n clustering conditions", 
       x="Contamination Level", y="F1 Measure") +
  #ylim(0,1) +
  theme_classic()
ggsave("HSP.NoBLoC.contamination.conditions.f1measure.pdf", 
       width=5, height=3.5)
```





```{r}
ari_HSP0.1 = readRDS("/Users/ziyisong/Desktop/Project_HSP/new.simulations/compare.HSP.NoBLoC/Contamination0.1/contamination0.1.ari_HSP.RDS")
f1measure_HSP0.1 = readRDS("/Users/ziyisong/Desktop/Project_HSP/new.simulations/compare.HSP.NoBLoC/Contamination0.1/contamination0.1.f1measure_HSP.RDS")
ari_NoBLoC0.1 = readRDS("/Users/ziyisong/Desktop/Project_HSP/new.simulations/compare.HSP.NoBLoC/Contamination0.1/contamination0.1.ari_NoBLoC.RDS")
f1measure_NoBLoC0.1 = readRDS("/Users/ziyisong/Desktop/Project_HSP/new.simulations/compare.HSP.NoBLoC/Contamination0.1/contamination0.1.f1measure_NoBLoC.RDS")

ari_HSP0.2 = readRDS("/Users/ziyisong/Desktop/Project_HSP/new.simulations/compare.HSP.NoBLoC/Contamination0.2/contamination0.2.ari_HSP.RDS")
f1measure_HSP0.2 = readRDS("/Users/ziyisong/Desktop/Project_HSP/new.simulations/compare.HSP.NoBLoC/Contamination0.2/contamination0.2.f1measure_HSP.RDS")
ari_NoBLoC0.2 = readRDS("/Users/ziyisong/Desktop/Project_HSP/new.simulations/compare.HSP.NoBLoC/Contamination0.2/contamination0.2.ari_NoBLoC.RDS")
f1measure_NoBLoC0.2 = readRDS("/Users/ziyisong/Desktop/Project_HSP/new.simulations/compare.HSP.NoBLoC/Contamination0.2/contamination0.2.f1measure_NoBLoC.RDS")

ari_HSP0.3 = readRDS("/Users/ziyisong/Desktop/Project_HSP/new.simulations/compare.HSP.NoBLoC/Contamination0.3/contamination0.3.ari_HSP.RDS")
f1measure_HSP0.3 = readRDS("/Users/ziyisong/Desktop/Project_HSP/new.simulations/compare.HSP.NoBLoC/Contamination0.3/contamination0.3.f1measure_HSP.RDS")
ari_NoBLoC0.3 = readRDS("/Users/ziyisong/Desktop/Project_HSP/new.simulations/compare.HSP.NoBLoC/Contamination0.3/contamination0.3.ari_NoBLoC.RDS")
f1measure_NoBLoC0.3 = readRDS("/Users/ziyisong/Desktop/Project_HSP/new.simulations/compare.HSP.NoBLoC/Contamination0.3/contamination0.3.f1measure_NoBLoC.RDS")
```






```{r}
library("reshape2")
library("ggplot2")
dat = data.frame("10 %" = c(ari_HSP0.1, ari_NoBLoC0.1),
           "20 %" = c(ari_HSP0.2, ari_NoBLoC0.2),
           "30 %" = c(ari_HSP0.3, ari_NoBLoC0.3),
           Model = c(rep("HSP",50), rep("NoB-LoC",50)),
           check.names = FALSE
           )
dat_long = melt(dat, id="Model")
ggplot(dat_long, aes(x=variable, y=value, color=Model)) +
  geom_boxplot(notch=FALSE) +
  labs(title="ARI: clustering subjects", x="Contamination Level", y="Adjusted Rand Index") +
  #ylim(0,1) +
  theme_classic()
ggsave("HSP.NoBLoC.contamination.subjects.ari.pdf", 
       width=5, height=3.5)
```





```{r}
dat = data.frame("10 %" = c(f1measure_HSP0.1, f1measure_NoBLoC0.1),
           "20 %" = c(f1measure_HSP0.2, f1measure_NoBLoC0.2),
           "30 %" = c(f1measure_HSP0.3, f1measure_NoBLoC0.3),
           Model = c(rep("HSP",50), rep("NoB-LoC",50)),
           check.names = FALSE
           )
dat_long = melt(dat, id="Model")
ggplot(dat_long, aes(x=variable, y=value, color=Model)) +
  geom_boxplot(notch=FALSE) +
  labs(title="F1-Measure: clustering subjects", x="Contamination Level", y="F1-Measure") +
  #ylim(0,1) +
  theme_classic()
ggsave("HSP.NoBLoC.contamination.subjects.f1measure.pdf", 
       width=5, height=3.5)
```










