

```{r}
rm(list=ls())
```



```{r}
ari_NoBLoC.subjects = readRDS("/Users/ziyisong/Desktop/Project_HSP/new.simulations/compare.HSP.NoBLoC/No.Contamination/ari_NoBLoC.subjects.RDS")
f1measure_NoBLoC.subjects = readRDS("/Users/ziyisong/Desktop/Project_HSP/new.simulations/compare.HSP.NoBLoC/No.Contamination/f1measure_NoBLoC.subjects.RDS")
ari_HSP.subjects = readRDS("/Users/ziyisong/Desktop/Project_HSP/new.simulations/compare.HSP.NoBLoC/No.Contamination/ari_HSP.subjects.RDS")
f1measure_HSP.subjects = readRDS("/Users/ziyisong/Desktop/Project_HSP/new.simulations/compare.HSP.NoBLoC/No.Contamination/f1measure_HSP.subjects.RDS")
```



```{r}
TTT = data.frame(ARI=c(ari_HSP.subjects, ari_NoBLoC.subjects), Model=c(rep("HSP",50),rep("NoB-LoC",50)))
TTT$Model = as.factor(TTT$Model)
library(ggplot2)
ggplot(TTT, aes(x=Model, y=ARI, fill=Model )) + 
  geom_boxplot(notch=FALSE) + 
  labs(title="ARI: clustering subjects", x="Models", y="Adjusted Rand Index") +
  ylim(0,1) +
  theme_classic()
ggsave("HSP.NoBLoC.subjects.ari.pdf", 
       width=5, height=3.5)
```



```{r}
TTT = data.frame(F1_Measure=c(f1measure_HSP.subjects, f1measure_NoBLoC.subjects), Model=c(rep("HSP",50),rep("NoB-LoC",50)))
TTT$Model = as.factor(TTT$Model)
library(ggplot2)
ggplot(TTT, aes(x=Model, y=F1_Measure, fill=Model )) + 
  geom_boxplot(notch=FALSE) + 
  labs(title="F1-Measure: clustering subjects", x="Models", y="F1-Measure") +
  ylim(0,1) + 
  theme_classic()
ggsave("HSP.NoBLoC.subjects.f1measure.pdf", 
       width=5, height=3.5)
```




```{r}
ari_NoBLoC.subjects.avg = readRDS("/Users/ziyisong/Desktop/Project_HSP/new.simulations/compare.HSP.NoBLoC/No.Contamination/ari_NoBLoC.subjects.avg.RDS")
f1measure_NoBLoC.subjects.avg = readRDS("/Users/ziyisong/Desktop/Project_HSP/new.simulations/compare.HSP.NoBLoC/No.Contamination/f1measure_NoBLoC.subjects.avg.RDS")
ari_HSP.subjects.avg = readRDS("/Users/ziyisong/Desktop/Project_HSP/new.simulations/compare.HSP.NoBLoC/No.Contamination/ari_HSP.subjects.avg.RDS")
f1measure_HSP.subjects.avg = readRDS("/Users/ziyisong/Desktop/Project_HSP/new.simulations/compare.HSP.NoBLoC/No.Contamination/f1measure_HSP.subjects.avg.RDS")
```



```{r}
TTT = data.frame(ARI.subjects.avg=c(ari_HSP.subjects.avg, ari_NoBLoC.subjects.avg),
                 Model=c(rep("HSP",50),rep("NoB-LoC",50)))
TTT$Model = as.factor(TTT$Model)
library(ggplot2)
ggplot(TTT, aes(x=Model, y=ARI.subjects.avg, fill=Model )) + 
  geom_boxplot(notch=FALSE) + 
  labs(title="(averaged across subjects) \n ARI: clustering conditions", x="Models", y="Adjusted Rand Index") +
  #scale_fill_manual(values=c("#999999", "#E69F00")) + 
  # ylim(0,1) +
  theme_classic()
ggsave("HSP.NoBLoC.conditions.ari.pdf", 
       width=5, height=3.5)
```




```{r}
TTT = data.frame(F1Measure.subjects.avg=c(f1measure_HSP.subjects.avg, f1measure_NoBLoC.subjects.avg),
                 Model=c(rep("HSP",50),rep("NoB-LoC",50)))
TTT$Model = as.factor(TTT$Model)
library(ggplot2)
ggplot(TTT, aes(x=Model, y=F1Measure.subjects.avg, fill=Model )) + 
  geom_boxplot(notch=FALSE) + 
  labs(title="(averaged across subjects) \n F1-Measure: clustering conditions", x="Models", y="F1 Measure") +
  #scale_fill_manual(values=c("#999999", "#E69F00")) + 
  # ylim(0,1) +
  theme_classic()
ggsave("HSP.NoBLoC.conditions.f1measure.pdf", 
       width=5, height=3.5)
```









